# cspell:words autofix, markdownlint, mdformat, shfmt, autoflake, Autoflake
# cspell:words isort, mypy, Mypy
---
repos:
-
  hooks:
  -
    entry: './src/sh/ensure-shebang.sh'
    id: 'ensure-shebang'
    language: 'script'
    name: 'ensure shebang'
    types:
    - 'shell'
  -
    entry: 'poetry run python ./src/python/hooks/src/file-name-conventions.py'
    id: 'file-name-conventions'
    language: 'system'
    name: 'ensure file name conventions'
  -
    entry: |
      poetry run autoflake -i --remove-all-unused-imports
      --remove-unused-variables --ignore-init-module-imports
    id: 'autoflake'
    language: 'system'
    name: 'autoflake'
    types:
    - 'python'
  -
    entry: 'poetry run black'
    id: 'black'
    language: 'system'
    name: 'black'
    types:
    - 'python'
  -
    entry: 'poetry run flake8'
    id: 'flake8'
    language: 'system'
    name: 'flake8'
    types:
    - 'python'
  -
    entry: 'poetry run isort'
    id: 'isort'
    language: 'system'
    name: 'isort'
    types:
    - 'python'
  -
    entry: 'poetry run mypy'
    id: 'mypy'
    language: 'system'
    name: 'mypy'
    types:
    - 'python'
  repo: 'local'
-
  hooks:
  - id: 'check-added-large-files'
  - id: 'check-case-conflict'
  - id: 'detect-private-key'
  - id: 'end-of-file-fixer'
  -
    files: 'cfg/cspell-dictionary.txt'
    id: 'file-contents-sorter'
  - id: 'mixed-line-ending'
  -
    args:
    - '--autofix'
    id: 'pretty-format-json'
  - id: 'trailing-whitespace'
  repo: 'https://github.com/pre-commit/pre-commit-hooks'
  rev: 'v4.5.0'
-
  hooks:
  - additional_dependencies:
    - 'mdformat-gfm'
    id: 'mdformat'
  repo: 'https://github.com/executablebooks/mdformat'
  rev: '0.7.17'
-
  hooks:
  -
    args:
    - '--config'
    - 'cfg/markdownlint-config.yaml'
    id: 'markdownlint-fix'
  repo: 'https://github.com/igorshubovych/markdownlint-cli'
  rev: 'v0.39.0'
-
  hooks:
  -
    args:
    - '--autofix'
    id: 'pretty-format-toml'
  repo: 'https://github.com/macisamuele/language-formatters-pre-commit-hooks'
  rev: 'v2.12.0'
-
  hooks:
  -
    args:
    - '--config-file'
    - 'cfg/yamllint-config.yaml'
    - '--strict'
    id: 'yamllint'
  repo: 'https://github.com/adrienverge/yamllint'
  rev: 'v1.34.0'
-
  hooks:
  - id: 'shfmt'
  repo: 'https://github.com/scop/pre-commit-shfmt'
  rev: 'v3.7.0-4'
-
  hooks:
  -
    args:
    - '--config'
    - 'cfg/cspell-config.json'
    id: 'cspell'
  repo: 'https://github.com/streetsidesoftware/cspell-cli'
  rev: 'v8.3.0'
...
