repos:
-
  hooks:
  - id: 'check-added-large-files'
  - id: 'check-case-conflict'
  - id: 'detect-private-key'
  - id: 'end-of-file-fixer'
  - id: 'mixed-line-ending'
  - id: 'trailing-whitespace'
  repo: 'https://github.com/pre-commit/pre-commit-hooks'
  rev: 'v2.3.0'
-
  hooks:
  - id: 'mdformat'
  repo: 'https://github.com/executablebooks/mdformat'
  rev: '0.7.17'
-
  hooks:
  - id: 'markdownlint-fix'
  repo: 'https://github.com/igorshubovych/markdownlint-cli'
  rev: 'v0.39.0'
-
  hooks:
  -
    args:
    - '--autofix'
    id: 'pretty-format-toml'
  repo: 'https://github.com/macisamuele/language-formatters-pre-commit-hooks'
  rev: 'v2.12.0'
-
  hooks:
  -
    args:
    - '--config-file'
    - 'cfg/yamllint-config.yaml'
    id: 'yamllint'
  repo: 'https://github.com/adrienverge/yamllint'
  rev: 'v1.33.0'
-
  hooks:
  - id: 'shfmt'
  repo: 'https://github.com/scop/pre-commit-shfmt'
  rev: 'v3.7.0-4'
