---
extends: 'default'
rules:
  braces:
    forbid: true
  brackets:
    forbid: true
  comments:
    ignore-shebangs: true
    level: 'error'
    min-spaces-from-content: 1
    require-starting-space: true
  comments-indentation:
    level: 'error'
  document-end: 'enable'
  document-start:
    level: 'error'
  empty-lines:
    max: 0
    max-end: 1
    max-start: 0
  empty-values: 'enable'
  float-values:
    forbid-inf: false
    forbid-nan: false
    forbid-scientific-notation: true
    require-numeral-before-decimal: true
  indentation:
    check-multi-line-strings: true
    indent-sequences: false
    spaces: 2
  key-ordering: 'enable'
  octal-values: 'enable'
  quoted-strings:
    quote-type: 'single'
    required: true
  truthy:
    level: 'error'
...
