[addresses]
econia = '_'

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-addresses]
econia = 'red_black_map'

[dev-dependencies]

[package]
authors = ["Econia Labs (developers@econialabs.com)"]
name = "RedBlackMap"
upgrade_policy = "compatible"
version = "0.1.0"
