[addresses]
econia = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-addresses]
econia = "0xc0de"

[package]
authors = ["Econia Labs (developers@econialabs.com)"]
name = "Econia"
upgrade_policy = "compatible"
version = "5.0.0"
